[package]
name = "amnis"
version = "0.0.1"
authors = ["Ivan Velichko <iximiuz@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
regex = "1.3.6"
serde_json = "1.0.51"
structopt = "0.3.13"

